### ISSUE TITLE
API URL is api.domain_name vs domain_name/api

### ISSUE THREAD

**Issue by JusteLeblanc** [theodo/theodo-stack-generator#123]
- [ ] Update NGINX conf
- [ ] Update documentation
- [ ] Specify a domain and not IP adress to access to local (10.0.0.10)

![](https://user-images.githubusercontent.com/9215726/36317193-bc3f34d2-133c-11e8-9e78-79ba36a26ec4.jpeg)

**Comment by benja-M-1** [comment]
duplicates #82

**Comment by benja-M-1** [comment]
@phacks we need you on that. We want to implement what you recommend for performances. Could you help us?

**Comment by MaximeThoonsen** [comment]
Hello @benja-M-1 and @phacks and @JusteLeblanc ,

I think we should also consider the devops aspect. From the LVMH experience, it was a problem that the api was in /api and not in api. It added complexity because of the proxy pass that we needed to add to the nginx conf. I sadly don't recall exactly the problem :/.

Anyway, if we want to reduce the OPTIONS requests impact, I find some links:
- https://gooroo.io/GoorooTHINK/Article/16408/Two-Strategies-for-Crossing-Origins-with-Performance-in-Mind/19880. _"Instead, the CORS specification introduces a new header: Access-Control-Max-Age. Access-Control-Max-Age has a simple numeric value, indicating the number of seconds in which the browser should cache a preflight response. For best effect, set the value of Access-Control-Max-Age to the longest duration that you can stomach"_
- https://medium.com/@praveen.beatle/avoiding-pre-flight-options-calls-on-cors-requests-baba9692c21a. The author is doing more or less our solution and If find this in the comments: _"This is not a sound architectural decision to route all your traffic to a proxy just to handle CORS preflight requests. You introduce a single point of a failure, a possible bottleneck, and increase latency which possibly negates your original goal."_ It can create problems when the app needs to scale
- https://damon.ghost.io/killing-cors-preflight-requests-on-a-react-spa/. _"IF you have CORS preflight requests and latency significant users: 1) Use the preflight cache 2) Make sure GET requests are simple"_ 
- https://dzone.com/articles/solving-the-options-performance-issue-with-single _"Adding custom headers or using a non-standard content-type forces the browser to issue a preflight OPTIONS request to determine if these are acceptable or not, and this effectively doubles the latency of fetching data"_

This subject is really big, we could make a conf only on this =).

One other thing is for the deployment, it is easier to use api.mydomain. For example, if we use AWS, we could push the front on S3 and the API on a EC2/Beanstalk/Serverless. if we don't want to have to mange an Api Gateway.
 
Bonus question, If we want to use the "text/plain" header to avoid the CORS, it could create security issues ? cc @clement-escolano @Paulmolin .

**Comment by clement-escolano** [comment]
@MaximeThoonsen Where did you read that using `test/plain` avoid CORS? I would like to investgate this as I wasn't aware of this and in order to see if there are possible security issues about it.

**Comment by MaximeThoonsen** [comment]
@clement-escolano in almost all links above :)
"
_> If the Content-Type header has a value

application/x-www-form-urlencoded
multipart/form-data
text/plain
"_

**Comment by clement-escolano** [comment]
@MaximeThoonsen OK I see. I will check but my estimate is that it is not a problem security-wise.

**Comment by phacks** [comment]
@MaximeThoonsen Thanks for the detailed and thorough explanation!

Two small comments:

> https://damon.ghost.io/killing-cors-preflight-requests-on-a-react-spa/. "IF you have CORS preflight requests and latency significant users: 1) Use the preflight cache 2) **Make sure GET requests are simple**"

Any `GET` request containing the `Authorization` header will not be considered _simple_ and will be preflighted, and if I remember correctly we use this header in the Generator to handle authentication. ([Source](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Simple_requests))

For the `application/json` vs `text/plain` issue, this [StackOverflow response](https://stackoverflow.com/a/4351090) explains that while it _may not_ be introducing performance or compatibility issue, it is generally a bad idea to break the HTTP convention over content types. I’m afraid some future issue will be caused by this and hard to debug.

**Comment by phacks** [comment]
@MaximeThoonsen Forgot to mention it but I’d be okay for your solution (`api.mydomain.com`) under the condition that the CORS cache is correctly set up so that the performance impacts are minimized :)
We can split this issue in two if you need me to take care of CORS configuration!

**Comment by MaximeThoonsen** [comment]
@phacks Ok I had the same conclusion. I think there is enough things to say for a good article ;)
OK for me to split into two issues cc @benja-M-1 @JusteLeblanc

**Comment by phacks** [comment]
Oh, just found something interesting re: preflight cache ([source](https://medium.com/@ankur_anand/the-terrible-performance-cost-of-cors-api-on-the-single-page-application-spa-6fcf71e50147)):

> You might say yes but then we can use the Access-Control-Max-Age header to cache the results of a preflight request, so that next time when we access a resource api.example.com/users/report/12345 from spa.example.com there is no preflight request.

> Yes that’s true, but then remember the title — The Terrible Performance Cost Of CORS Request, on the single-page application (SPA), comes from the API that we’re are consuming and the way it’s has been designed. In our example, we designed our API /users/report/:id, where :id means its a value that can change.

> The way preflight cache work is per URL not just the origin, meaning that any change in the path, (which includes query parameters) warrants another preflight request.

> So In our case to access resource api.example.com/users/report/12345 and api.example.com/users/report/123987 will trigger to 4 requests from our SPA in total.

Meaning that preflight cache probably isn’t a good option for our use-case (I figure most of Theodo’s webapps today make requests to a lot of `/:id` through navigation).

Back to square one 😣

**Comment by MaximeThoonsen** [comment]
OK. So let's say that we go /api and we will let the devops handle the problems with some gateway. After all I was trying to prevent a devops problem but the final customers (and so the perf of the app) are more important. 
I suggest we go to /api and if we found a way of fixing this problem we go back to api. 
OK @benja-M-1 @JusteLeblanc @phacks ?

**Comment by benja-M-1** [comment]
> One other thing is for the deployment, it is easier to use api.mydomain. For example, if we use AWS, we could push the front on S3 and the API on a EC2/Beanstalk/Serverless. if we don't want to have to mange an Api Gateway.

With a reverse proxy you can deploy any apps wherever you want. So it is not a blocker to me.

So the question now is who is willing to investigate on this?

**Comment by MaximeThoonsen** [comment]
@benja-M-1 yes I agree it's not a blocker.

> So the question now is who is willing to investigate on this?

What do you mean ? Who is willing to perform the changes ? I think it's already /api in the nginx template so there is nothing to do.

If you are speaking about how we deploy on AWS I think we can wait to see with Wilko.

**Comment by JusteLeblanc** [comment]
It's time to close this issue. Feel free to re-open it if we found a way to fix it.
